# Generated by Django 3.1.1 on 2020-09-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Employee',
        ),
    ]
